name: Update Browserslist database

on:
  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-browserslist-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: yettoapp/actions/setup-languages@main
        with:
          node: true

      - run: npx update-browserslist-db@latest

      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.token }}
          commit-message: "[auto-browserslist] Update Browserslist db"
          title: "[auto-browserslist] Update Browserslist db"
          body: |
            - Update Browserslist information
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: browserslist-update
          committer: Sisyphus <sisyphus@yetto.app>
          author: Sisyphus <sisyphus@yetto.app>
          delete-branch: true
          labels: "chore, github action"

      - name: Enable Pull Request Automerge
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
